import json
from utilities import parse_courses

sts = parse_courses([
"ABE 22600 - Biotechnology Laboratory I",
"ABE 29000 - Sophomore Seminar",
"AD 39500 - History of Design (Fall 2021 and after only)",
"AGRY 12500 - Environmental Science and Conservation",
"AGRY 28500 - World Crop Adaptation and Distribution",
"AGRY 29000 - Introduction to Environmental Science",
"AMST 31000 - Invention, Innovation, Design",
"AMST 32500 - Sports, Technology and Innovation",
"ANSC 10200 - Intro to Animal Agriculture",
"ANTH 21000 - Technology and Culture",
"ASEC 35500 - Controversial Science and Media in the Public Sphere",
"ASM 23600 - Environmental Systems Management",
"BCHM 10000 - Intro to Biochemistry",
"BCM 10001 - Introduction to Construction Management",
"BIOL 12100 - Biology I: Ecology, Diversity, & Behavior",
"BIOL 31200 - Great Issues in Genomics and Society  (Fall 2015 and earlier only)",
"BTNY 20100 - Plants and Civilization",
"BTNY 21100 - Plants and the Environment",
"BTNY 28500 - Plants and Civilization",
"CM 10000 - Introduction to Construction",
"COM 25100 - Intro to Electronic Mass Media",
"COM 25100 - Communication, Information and Society",
"CS 10100 - Digital Literacy",
"EAPS 10000 - Planet Earth",
"EAPS 10400 - Oceanography",
"EAPS 10600 - Geosciences in the Cinema",
"EAPS 11300 - Introduction to Environmental Science",
"EAPS 12000 - Introduction to Geography",
"EAPS 12500 - Environmental Science and Conservation",
"EAPS 12900 - Earth System Dynamics",
"EAPS 20000 - Water World: Processes and Challenges in Global Hydrology",
"EEE 35500 - Engineering Environmental Sustainability (Fall 2020 and after only)",
"ENGL 22300 - Literature and Technology",
"ENGL 22600 - Narrative Medicine",
"ENGL 23400 - Ecological Literature",
"ENGR 20100 - Engineering in Global Context (Summer 2016 and earlier only, course renumbered to ENGR 31000)",
"ENGR 27920 - Sophomore Participation In Vertically Integrated Projects (VIP) (Fall 2020 only, course prefix changed to VIP)",
"ENGR 31000 - Engineering in Global Context (Fall 2016 and after only, course renumbered from ENGR 20100) ",
"ENGR 37920 - Junior Participation In Vertically Integrated Projects (VIP) (Fall 2020 only, course prefix changed to VIP)",
"ENGR 47920 - Senior Participation In Vertically Integrated Projects (VIP) (Fall 2020 only, course prefix changed to VIP)",
"ENTM 10500 - Insects: Friends & Foe",
"ENTM 12800 - Investigating Forensic Science",
"ENTM 21800 - Intro to Forensic Science (Fall 2014 and earlier only)",
"EPCS 10100 - Engineering Projects in Community Service",
"EPCS 10200 - Engineering Projects in Community Service",
"EPCS 11100 - First Year Participation in EPICS I",
"EPCS 12100 - First Year Participation in EPICS I",
"EPCS 20100 - Engineering Projects in Community Service",
"EPCS 20200 - Engineering Projects in Community Service",
"EPCS 30100 - Engineering Projects in Community Service",
"EPCS 30200 - Engineering Projects in Community Service",
"EPCS 40100 - Engineering Projects in Community Service",
"EPCS 40200 - Engineering Projects in Community Service",
"FNR 10300 - Intro to Environmental Conservation",
"FNR 12500 - Environmental Science and Conservation",
"FNR 22310 - Introduction to Environmental Policy",
"FNR 23000 - World Forests and Society",
"FNR 24000 - Wildlife in America",
"FS 16100 - Science of Food",
"HIST 30305 - Food in Modern America",
"HIST 30605 - Technology And War In U.S. History ",
"HIST 31305 - Medical Devices and Innovation",
"HIST 31405 - Science, Technology, Engineering And Mathematics (STEM) And Gender",
"HIST 33205 - The Nuclear Age",
"HIST 33300 - Science & Society in Western Civilization I",
"HIST 33400 - Science & Society in Western Civilization II",
"HIST 35000 - Science & Society in the Twentieth Century World",
"HIST 35205 - Death, Disease and Medicine in Twentieth-Century American History",
"HIST 36305 - The History of Medicine and Public Health",
"HIST 38001 - History of U. S. Agriculture",
"HIST 38400 - History of Aviation",
"HIST 38700 - History of the Space Age",
"HONR 19901 - The Evolution of Ideas  (Fall 2018 and earlier ONLY)",
"HORT 12100 - Medicine in the Garden",
"HORT 30600 - History of Horticulture",
"HSCI 20100 - Principles of Public Health Science",
"HSCI 20200 - Essentials of Environmental, Occupational, & Radiological Health Sciences",
"IT 22600 - Biotechnical Lab I",
"LA 16100 - Land and Society",
"ME 29000 - Global Engineering Professional Seminar",
"NRES 12500 - Environmental Science and Conservation",
"NRES 29000 - Introduction to Environmental Science",
"NUTR 39800 - Culture & Food of France",
"PHIL 20700 - Ethics for Technology, Engineering, and Design",
"PHIL 22100 - Introduction to Philosophy of Science",
"PHIL 27000 - Biomedical Ethics",
"POL 22300 - Introduction to Environmental Policy",
"POL 23700 - Modern Weapons and International Relations",
"PUBH 20200 - Health in the Time of Pandemics: An Introduction (Fall 2020 and after only)",
"SA 10202 - Culture & Food of France",
"SLHS 11500 - Introduction to Communicative Disorders",
"SLHS 21500 - Exploring Audiology & Hearing Science",
"SLHS 30900 - Language Development",
"SOC 33500 - Political Sociology (Fall 2021 and after only)",
"STAT 11300 - Statistics and Society",
"SYS 30000 - It’s a Complex World: Addressing Global Challenges",
"SYS 35000 - Systems Theories and Approaches ( Summer 2021 and earlier only)",
"SYS 40000 - Systems Praxis (Fall 2021 and after only)",
"TECH 12000 - Technology and the Individual  (Fall 2013 and after only)",
"VIP 27920 - Sophomore Participation In Vertically Integrated Projects (VIP) (Spring 2021 and after only)",
"VIP 37920 - Junior Participation In Vertically Integrated Projects (VIP) (Spring 2021 and after only)",
"VIP 47920 - Senior Participation In Vertically Integrated Projects (VIP) (Spring 2021 and after only)",
"YDAE 35500 - Controversial Science and Media in the Public Sphere (Summer 2019 and before only. Effective Fall 2019, YDAE is now ASEC)",
])

sts = {
	"title": "Science, Technology, and Society (STS)",
	"type": "or",
	"value": sts
}

with open("ucore/sts.json", "w") as file:
	file.write(json.dumps(sts, indent=4))